using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Myitian.LiteProtobuf.SourceGeneration;

[Generator]
internal class DefaultTryCreateFulfilledGenerator : IIncrementalGenerator
{
    public const string Global = "global::";
    public const string N_DefaultTryCreateFulfilledAttribute = "DefaultTryCreateFulfilledAttribute";

    public const string NS_Myitian = nameof(Myitian);
    public const string NS_Myitian_LiteProtobuf = $"{NS_Myitian}.{nameof(LiteProtobuf)}";
    public const string NS_Myitian_LiteProtobuf_SourceGeneration = $"{NS_Myitian_LiteProtobuf}.{nameof(SourceGeneration)}";

    public const string FQ_DefaultTryCreateFulfilledAttribute = $"{NS_Myitian_LiteProtobuf_SourceGeneration}.{N_DefaultTryCreateFulfilledAttribute}";

    public const string FQG_NotNullWhenAttribute = $"{Global}System.Diagnostics.CodeAnalysis.NotNullWhenAttribute";
    public const string FQG_IStructBinaryReader = $"{Global}{NS_Myitian_LiteProtobuf}.IStructBinaryReader";
    public const string FQG_IClassBinaryReader = $"{Global}{NS_Myitian_LiteProtobuf}.IClassBinaryReader";
    public const string FQG_ParseStatus = $"{Global}{NS_Myitian_LiteProtobuf}.ParseStatus";
    public const string FQG_WireType = $"{Global}{NS_Myitian_LiteProtobuf}.WireType";
    public const string FQG_Defaults = $"{Global}{NS_Myitian_LiteProtobuf}.Defaults";

    public const string AttributeSource = $$"""
            // <auto-generated />
            using System;
            namespace {{NS_Myitian_LiteProtobuf_SourceGeneration}}
            {
                [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
                sealed class {{N_DefaultTryCreateFulfilledAttribute}} : Attribute
                {
                    public {{N_DefaultTryCreateFulfilledAttribute}}(Type arg) { }
                }
            }
            """;
    public const string Template = $$$"""
        public static bool TryCreateFulfilled<TReader>(
            scoped ref TReader reader,
            {{{FQG_WireType}}} wireType,
            [{{{FQG_NotNullWhenAttribute}}}(true)] out {0} value,
            out {{{FQG_ParseStatus}}} status)
            where TReader : struct, {{{FQG_IStructBinaryReader}}}<TReader>, allows ref struct
        {{
            return {{{FQG_Defaults}}}<{1}>.TryCreateFulfilled(ref reader, wireType, out value, out status);
        }}
        public static bool TryCreateFulfilled<TReader>(
            TReader reader,
            {{{FQG_WireType}}} wireType,
            [{{{FQG_NotNullWhenAttribute}}}(true)] out {0} value,
            out {{{FQG_ParseStatus}}} status)
            where TReader : class, {{{FQG_IClassBinaryReader}}}<TReader>
        {{
            return {{{FQG_Defaults}}}<{1}>.TryCreateFulfilled(reader, wireType, out value, out status);
        }}
        """;
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
            postInitializationContext.AddSource(
                $"{N_DefaultTryCreateFulfilledAttribute}.g.cs",
                AttributeSource));

        context.RegisterSourceOutput(context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: FQ_DefaultTryCreateFulfilledAttribute,
            predicate: static (syntaxNode, _) => syntaxNode is BaseTypeDeclarationSyntax,
            transform: static (context, _) => new Model(context))
            .Where(it => it.IsValid)
            .Combine(context.CompilationProvider), Apply);
    }
    public static void Apply(SourceProductionContext context, (Model Model, Compilation Compilation) model)
    {
        if (model.Model is not { Self: INamedTypeSymbol self })
            return;
        StringBuilder sb = new();
        int depth = sb.AppendCSharpCode("", self);
        foreach (INamedTypeSymbol arg in model.Model.Args)
        {
            ITypeSymbol symbol = arg.IsValueType ?
                arg : arg.WithNullableAnnotation(NullableAnnotation.Annotated);
            string c0 = symbol.ToDisplayString(Utils.NullableFullyQualifiedFormat);
            string c1 = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendIndented(depth, string.Format(Template, c0, c1));
        }
        while (depth > 0)
        {
            depth--;
            sb.Append(' ', depth * 4)
                .AppendLine("}");
        }
        string code = sb.ToString();
        context.AddSource($"{self.Name}.g.cs", code);
    }
    public readonly record struct Model
    {
        public bool IsValid => Self is not null && !Args.IsDefaultOrEmpty;
        public INamedTypeSymbol? Self { get; } = null;
        public ImmutableArray<INamedTypeSymbol> Args { get; }

        public Model(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol self)
                return;
            List<INamedTypeSymbol> args = [];
            foreach (AttributeData attr in context.Attributes)
            {
                if (attr is not
                    {
                        ConstructorArguments: [
                            {
                                Kind: TypedConstantKind.Type,
                                Value: INamedTypeSymbol arg
                            }]
                    })
                    return;
                args.Add(arg);
            }
            Self = self;
            Args = [.. args];
        }
    }
}
