using Microsoft.CodeAnalysis;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Text;

namespace Myitian.LiteProtobuf.SourceGeneration;

static class Extension
{
    extension(StringBuilder sb)
    {
        public StringBuilder AppendClrName(ITypeSymbol symbol)
        {
            if (symbol.ContainingType != null)
                sb.AppendClrName(symbol.ContainingType).Append('+');
            else if (symbol.ContainingNamespace != null && !symbol.ContainingNamespace.IsGlobalNamespace)
                sb.Append(symbol.ContainingNamespace.ToDisplayString()).Append('.');
            sb.Append(symbol.Name);
            if (symbol is INamedTypeSymbol namedType && namedType.Arity > 0)
                sb.Append('`').Append(namedType.Arity);
            return sb;
        }
        public StringBuilder AppendGeneratedFileName(string dir, ITypeSymbol symbol)
        {
            return sb.Append(dir).Append(Path.DirectorySeparatorChar).AppendClrName(symbol).Append(".g.cs");
        }
    }
    extension(IndentedTextWriter writer)
    {
        public void WriteCSharpHeader(string? extra = null)
        {
            writer.WriteLine("// <auto-generated />");
            if (extra is not null)
                writer.WriteLine(extra);
            writer.WriteLine("#nullable enable");
        }
        public void BeginCSharpTypeBlock(INamedTypeSymbol type)
        {
            if (!string.IsNullOrWhiteSpace(type.ContainingNamespace.Name))
            {
                writer.WriteLine();
                writer.Write("namespace ");
                writer.WriteLine(type.ContainingNamespace.ToDisplayString());
                writer.BeginCodeBlock();
            }
            writer.WriteCSharpTypeDef(type);
        }
        public void EndCSharpTypeBlock()
        {
            while (writer.Indent > 0)
                writer.EndCodeBlock();
        }
        public void WriteCSharpTypeDef(INamedTypeSymbol type)
        {
            if (type.ContainingType is not null)
                writer.WriteCSharpTypeDef(type.ContainingType);
            writer.Write("partial ");
            writer.Write(type.IsRecord ? "record " : "");
            writer.Write(type.IsValueType ? "struct " : "class ");
            writer.WriteLine(type.ToDisplayString(MainGenerator.DeclarationFormat));
            writer.BeginCodeBlock();
        }
        public void BeginCodeBlock()
        {
            writer.WriteLine('{');
            writer.Indent++;
        }
        public void EndCodeBlock()
        {
            writer.Indent--;
            writer.WriteLine('}');
        }
        public void WriteLines(string text, params object[] arg)
        {
            using StringReader sr = new(text);
            while (sr.ReadLine() is string line)
                writer.WriteLine(line, arg);
        }
        public IndentedBlock IndentedBlock()
        {
            return new(writer);
        }
        public CodeBlock CodeBlock()
        {
            return new(writer);
        }
        public CSharpTypeBlock CSharpTypeBlock(INamedTypeSymbol type)
        {
            return new(writer, type);
        }
    }
    extension(Compilation compilation)
    {
        public INamedTypeSymbol? GetTypeByMetadataAndAssemblyName(
            string fullyQualifiedMetadataName,
            string? assemblyName = null)
        {
            ImmutableArray<INamedTypeSymbol> symbols = compilation.GetTypesByMetadataName(fullyQualifiedMetadataName);
            if (symbols.IsDefaultOrEmpty)
                return null;
            if (assemblyName is null)
                return symbols[0];
            return symbols.FirstOrDefault(s => s.ContainingAssembly.Name == assemblyName);
        }
    }
    extension(ITypeSymbol type)
    {
        public bool IsSymbolNullable([NotNullWhen(true)] out ITypeSymbol? parameter)
        {
            if (type is INamedTypeSymbol { SpecialType: SpecialType.System_Nullable_T, TypeArguments: [ITypeSymbol p] })
            {
                parameter = p;
                return true;
            }
            parameter = null;
            return false;
        }
        public IMethodSymbol? FindMethod(
            Compilation compilation,
            Func<IMethodSymbol, bool> predicate,
            Comparison<IMethodSymbol?>? comparison = null,
            Predicate<IMethodSymbol>? earlyReturn = null)
        {
            IMethodSymbol? candidate = default;
            ITypeSymbol? currentType = type;
            while (currentType is not null)
            {
                foreach (IMethodSymbol member in type.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(it => it.MethodKind is MethodKind.Ordinary
                              && it.CanBeReferencedByName
                              && compilation.IsSymbolAccessibleWithin(it, type, type))
                    .Where(predicate))
                {
                    if (earlyReturn?.Invoke(member) is true)
                        return member;
                    if (comparison?.Invoke(member, candidate) is null or > 0)
                        candidate = member;
                }
                currentType = currentType.BaseType;
            }
            return candidate;
        }
        public IEnumerable<ISymbol> AllAccessiblePropertiesAndFields(Compilation compilation)
        {
            ITypeSymbol? currentType = type;
            HashSet<string> memberNames = [];
            while (currentType is not null)
            {
                foreach (ISymbol member in type.GetMembers())
                {
                    if (member is IPropertySymbol or IFieldSymbol
                        && compilation.IsSymbolAccessibleWithin(member, type, type)
                        && memberNames.Add(member.Name))
                        yield return member;
                }
                currentType = currentType.BaseType;
            }
        }
    }
}