using Microsoft.CodeAnalysis;
// using System.Threading;

namespace Myitian.LiteProtobuf.SourceGeneration;

[Generator]
internal class MainGenerator : IIncrementalGenerator
{
    public const string Global = "global::";
    public const string N_DefaultTryCreateInstanceAttribute = $"Default{nameof(Defaults.TryCreateInstance)}Attribute";
    public const string N_DefaultCreateInstanceAttribute = $"Default{nameof(Defaults.CreateInstance)}Attribute";
    public const string N_DefaultTryCreateFulfilledAttribute = $"Default{nameof(Defaults.TryCreateFulfilled)}Attribute";
    public const string N_DefaultCreateFulfilledAttribute = $"Default{nameof(Defaults.CreateFulfilled)}Attribute";

    public const string NS_Myitian = nameof(Myitian);
    public const string NS_Myitian_LiteProtobuf = $"{NS_Myitian}.{nameof(LiteProtobuf)}";
    public const string NS_Myitian_LiteProtobuf_Serialization = $"{NS_Myitian_LiteProtobuf}.Serialization";
    public const string NS_Myitian_LiteProtobuf_SourceGeneration = $"{NS_Myitian_LiteProtobuf}.{nameof(SourceGeneration)}";
    public const string NS_System = nameof(System);
    public const string NS_System_Diagnostics = $"{NS_System}.{nameof(System.Diagnostics)}";
    public const string NS_System_Diagnostics_CodeAnalysis = $"{NS_System_Diagnostics}.{nameof(System.Diagnostics.CodeAnalysis)}";

    public const string FQ_DefaultTryCreateInstanceAttribute = $"{NS_Myitian_LiteProtobuf_SourceGeneration}.{N_DefaultTryCreateInstanceAttribute}";
    public const string FQ_DefaultCreateInstanceAttribute = $"{NS_Myitian_LiteProtobuf_SourceGeneration}.{N_DefaultCreateInstanceAttribute}";
    public const string FQ_DefaultTryCreateFulfilledAttribute = $"{NS_Myitian_LiteProtobuf_SourceGeneration}.{N_DefaultTryCreateFulfilledAttribute}";
    public const string FQ_DefaultCreateFulfilledAttribute = $"{NS_Myitian_LiteProtobuf_SourceGeneration}.{N_DefaultCreateFulfilledAttribute}";

    public const string FQG_NotNullWhenAttribute = $"{Global}{NS_System_Diagnostics_CodeAnalysis}.NotNullWhenAttribute";
    public const string FQG_IStructBinaryReader = $"{Global}{NS_Myitian_LiteProtobuf}.IStructBinaryReader";
    public const string FQG_IClassBinaryReader = $"{Global}{NS_Myitian_LiteProtobuf}.IClassBinaryReader";
    public const string FQG_ParseStatus = $"{Global}{NS_Myitian_LiteProtobuf}.ParseStatus";
    public const string FQG_WireType = $"{Global}{NS_Myitian_LiteProtobuf}.WireType";
    public const string FQG_Defaults = $"{Global}{NS_Myitian_LiteProtobuf}.Defaults";
    public const string FQG_FieldInfo = $"{Global}{NS_Myitian_LiteProtobuf_Serialization}.FieldInfo";
    public const string FQG_SerializationOptions = $"{Global}{NS_Myitian_LiteProtobuf_Serialization}.SerializationOptions";

    public const string AttributeSource = $$"""
            // <auto-generated />
            using System;
            namespace {{NS_Myitian_LiteProtobuf_SourceGeneration}}
            {
                [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
                public sealed class {{N_DefaultTryCreateInstanceAttribute}} : Attribute
                {
                    public {{N_DefaultTryCreateInstanceAttribute}}(Type arg) { }
                }
                [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
                public sealed class {{N_DefaultCreateInstanceAttribute}} : Attribute
                {
                    public {{N_DefaultCreateInstanceAttribute}}(Type arg) { }
                }
                [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
                public sealed class {{N_DefaultTryCreateFulfilledAttribute}} : Attribute
                {
                    public {{N_DefaultTryCreateFulfilledAttribute}}(Type arg) { }
                }
                [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = true)]
                public sealed class {{N_DefaultCreateFulfilledAttribute}} : Attribute
                {
                    public {{N_DefaultCreateFulfilledAttribute}}(Type arg) { }
                }
            }
            """;
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // new Thread(() => Thread.Sleep(100000)) { IsBackground = false }.Start(); // Keep console not to close
        context.RegisterPostInitializationOutput(static postInitializationContext =>
            postInitializationContext.AddSource(
                "Attributes.g.cs",
                AttributeSource));
        Defaults.RegisterSourceOutput(context, Defaults.TryCreateInstance.Instance);
        Defaults.RegisterSourceOutput(context, Defaults.CreateInstance.Instance);
        Defaults.RegisterSourceOutput(context, Defaults.TryCreateFulfilled.Instance);
        Defaults.RegisterSourceOutput(context, Defaults.CreateFulfilled.Instance);
    }
}
