using Microsoft.CodeAnalysis;
using System.CodeDom.Compiler;
using System.IO;
using System.Text;

namespace Myitian.LiteProtobuf.SourceGeneration;

static class Utils
{
    public static readonly SymbolDisplayFormat DeclarationFormat = new(
        SymbolDisplayGlobalNamespaceStyle.Omitted,
        SymbolDisplayTypeQualificationStyle.NameOnly,
        SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes);
    public static readonly SymbolDisplayFormat NullableFullyQualifiedFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);
    public static StringBuilder AppendClrName(this StringBuilder sb, ITypeSymbol symbol)
    {
        if (symbol.ContainingType != null)
            sb.AppendClrName(symbol.ContainingType).Append('+');
        else if (symbol.ContainingNamespace != null && !symbol.ContainingNamespace.IsGlobalNamespace)
            sb.Append(symbol.ContainingNamespace.ToDisplayString()).Append('.');
        sb.Append(symbol.Name);
        if (symbol is INamedTypeSymbol namedType && namedType.Arity > 0)
            sb.Append('`').Append(namedType.Arity);
        return sb;
    }
    public static void BeginCSharpCode(this IndentedTextWriter writer, string extra, INamedTypeSymbol type)
    {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine(extra);
        writer.WriteLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(type.ContainingNamespace.Name))
        {
            writer.WriteLine();
            writer.Write("namespace ");
            writer.WriteLine(type.ContainingNamespace.ToDisplayString());
            writer.BeginCodeBlock();
        }
        writer.WriteTypeDefCSharpCode(type);
    }
    public static void EndCSharpCode(this IndentedTextWriter writer)
    {
        while (writer.Indent > 0)
            writer.EndCodeBlock();
    }
    public static void WriteTypeDefCSharpCode(this IndentedTextWriter writer, INamedTypeSymbol type)
    {
        if (type.ContainingType is not null)
            writer.WriteTypeDefCSharpCode(type.ContainingType);
        writer.Write("partial ");
        writer.Write(type.IsRecord ? "record " : "");
        writer.Write(type.IsValueType ? "struct " : "class ");
        writer.WriteLine(type.ToDisplayString(DeclarationFormat));
        writer.BeginCodeBlock();
    }
    public static void BeginCodeBlock(this IndentedTextWriter writer)
    {
        writer.WriteLine('{');
        writer.Indent++;
    }
    public static void EndCodeBlock(this IndentedTextWriter writer)
    {
        writer.Indent--;
        writer.WriteLine('}');
    }
    public static void WriteLines(this IndentedTextWriter writer, string text, params object[] arg)
    {
        using StringReader sr = new(text);
        while (sr.ReadLine() is string line)
            writer.WriteLine(line, arg);
    }
    public static IndentedBlock IndentedBlock(this IndentedTextWriter writer)
    {
        return new(writer);
    }
    public static CodeBlock CodeBlock(this IndentedTextWriter writer)
    {
        return new(writer);
    }
}