using Microsoft.CodeAnalysis;
using System.IO;
using System.Text;

namespace Myitian.LiteProtobuf.SourceGeneration;

public static class Utils
{
    public static readonly SymbolDisplayFormat DeclarationFormat = new(
        SymbolDisplayGlobalNamespaceStyle.Omitted,
        SymbolDisplayTypeQualificationStyle.NameOnly,
        SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes);
    public static readonly SymbolDisplayFormat NullableFullyQualifiedFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);
    public static StringBuilder AppendClrName(this StringBuilder sb, ITypeSymbol symbol)
    {
        if (symbol.ContainingType != null)
            sb.AppendClrName(symbol.ContainingType).Append('+');
        else if (symbol.ContainingNamespace != null && !symbol.ContainingNamespace.IsGlobalNamespace)
            sb.Append(symbol.ContainingNamespace.ToDisplayString()).Append('.');
        sb.Append(symbol.Name);
        if (symbol is INamedTypeSymbol namedType && namedType.Arity > 0)
            sb.Append('`').Append(namedType.Arity);
        return sb;
    }
    public static int AppendCSharpCode(this StringBuilder sb, string usings, INamedTypeSymbol symbol)
    {
        int depth = 0;
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine(usings);
        sb.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(symbol.ContainingNamespace.Name))
        {
            sb.AppendLine()
                .Append("namespace ")
                .AppendLine(symbol.ContainingNamespace.ToDisplayString())
                .AppendLine("{");
            depth++;
        }
        sb.AppendTypeDefCSharpCode(symbol, ref depth);
        return depth;
    }
    public static void AppendTypeDefCSharpCode(this StringBuilder sb, INamedTypeSymbol type, ref int depth)
    {
        if (type.ContainingType is not null)
            sb.AppendTypeDefCSharpCode(type.ContainingType, ref depth);
        sb.Append(' ', depth * 4)
            .Append("partial ")
            .Append(type.IsRecord ? "record " : "")
            .Append(type.IsValueType ? "struct " : "class ")
            .Append(type.ToDisplayString(DeclarationFormat))
            .AppendLine();
        sb.Append(' ', depth * 4)
            .AppendLine("{");
        depth++;
    }
    public static void AppendIndented(this StringBuilder sb, int depth, string text)
    {
        using StringReader sr = new(text);
        while (sr.ReadLine() is string line)
            sb.Append(' ', depth * 4).AppendLine(line.ToString());
    }
}