//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myitian.LiteProtobuf.SourceGeneration.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myitian.LiteProtobuf.SourceGeneration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 This generator skips explicit interface implementations. To include this member, use a standard property or method implementation instead. 的本地化字符串。
        /// </summary>
        internal static string LPSG001_ExplicitInterfaceImplementationNotSupported_Description {
            get {
                return ResourceManager.GetString("LPSG001_ExplicitInterfaceImplementationNotSupported_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The member &apos;{0}&apos; will be ignored because explicit interface implementations are not supported 的本地化字符串。
        /// </summary>
        internal static string LPSG001_ExplicitInterfaceImplementationNotSupported_Message {
            get {
                return ResourceManager.GetString("LPSG001_ExplicitInterfaceImplementationNotSupported_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explicit interface implementation will be ignored 的本地化字符串。
        /// </summary>
        internal static string LPSG001_ExplicitInterfaceImplementationNotSupported_Title {
            get {
                return ResourceManager.GetString("LPSG001_ExplicitInterfaceImplementationNotSupported_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This generator does not support targeting the underlying field of an auto-implemented property. 的本地化字符串。
        /// </summary>
        internal static string LPSG002_AttributeOnBackingFieldNotSupported_Description {
            get {
                return ResourceManager.GetString("LPSG002_AttributeOnBackingFieldNotSupported_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute &apos;{0}&apos; cannot be applied to the backing field of property &apos;{1}&apos;. The member will be ignored by this generator. 的本地化字符串。
        /// </summary>
        internal static string LPSG002_AttributeOnBackingFieldNotSupported_Message {
            get {
                return ResourceManager.GetString("LPSG002_AttributeOnBackingFieldNotSupported_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute cannot be applied to compiler-generated backing field 的本地化字符串。
        /// </summary>
        internal static string LPSG002_AttributeOnBackingFieldNotSupported_Title {
            get {
                return ResourceManager.GetString("LPSG002_AttributeOnBackingFieldNotSupported_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This generator requires the target property to have a get accessor to read its value during code generation. 的本地化字符串。
        /// </summary>
        internal static string LPSG003_AttributeOnWriteOnlyPropertyNotSupported_Description {
            get {
                return ResourceManager.GetString("LPSG003_AttributeOnWriteOnlyPropertyNotSupported_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The attribute &apos;{0}&apos; cannot be applied to property &apos;{1}&apos; because it lacks a getter. The member will be ignored by this generator. 的本地化字符串。
        /// </summary>
        internal static string LPSG003_AttributeOnWriteOnlyPropertyNotSupported_Message {
            get {
                return ResourceManager.GetString("LPSG003_AttributeOnWriteOnlyPropertyNotSupported_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute cannot be applied to write-only properties 的本地化字符串。
        /// </summary>
        internal static string LPSG003_AttributeOnWriteOnlyPropertyNotSupported_Title {
            get {
                return ResourceManager.GetString("LPSG003_AttributeOnWriteOnlyPropertyNotSupported_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each ProtobufField attribute within the same class must have a unique tag number to ensure correct serialization. 的本地化字符串。
        /// </summary>
        internal static string LPSG004_DuplicateFieldNumber_Description {
            get {
                return ResourceManager.GetString("LPSG004_DuplicateFieldNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Protobuf field number &apos;{0}&apos; is already used by member &apos;{1}&apos;. The member will be ignored by this generator. 的本地化字符串。
        /// </summary>
        internal static string LPSG004_DuplicateFieldNumber_Message {
            get {
                return ResourceManager.GetString("LPSG004_DuplicateFieldNumber_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate Protobuf field number 的本地化字符串。
        /// </summary>
        internal static string LPSG004_DuplicateFieldNumber_Title {
            get {
                return ResourceManager.GetString("LPSG004_DuplicateFieldNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This generator requires the target type to implement a specific interface to ensure all required members are present. 的本地化字符串。
        /// </summary>
        internal static string LPSG005_MissingInterface_Description {
            get {
                return ResourceManager.GetString("LPSG005_MissingInterface_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; must implement the interface &apos;{1}&apos; to be processed by this generator 的本地化字符串。
        /// </summary>
        internal static string LPSG005_MissingInterface_Message {
            get {
                return ResourceManager.GetString("LPSG005_MissingInterface_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type does not implement required interface 的本地化字符串。
        /// </summary>
        internal static string LPSG005_MissingInterface_Title {
            get {
                return ResourceManager.GetString("LPSG005_MissingInterface_Title", resourceCulture);
            }
        }
    }
}
