using Microsoft.CodeAnalysis;
using System.CodeDom.Compiler;
using System.IO;
using System.Text;

namespace Myitian.LiteProtobuf.CompileTimeSourceGeneration.Templates;

static partial class DefaultHandler
{
    const string SharedHeader = """
        // <auto-generated />
        using Myitian.LiteProtobuf.Serialization.DefaultImplementation;
        using System.Diagnostics.CodeAnalysis;
        using System.Numerics;

        #nullable enable

        namespace Myitian.LiteProtobuf.Serialization.DefaultHandler;
        
        """;
    public static void RegisterAll(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(Generate);
    }
    static void Generate(IncrementalGeneratorPostInitializationContext context)
    {
        StringBuilder sb = new();
        // <list type="bullet">
        // <item><c>{0}</c>: base mode</item>
        // <item><c>{1}</c>: mode</item>
        // <item><c>{2}</c>: type param</item>
        // <item><c>{3}</c>: type param with comma</item>
        // <item><c>{4}</c>: private use (<c>&lt;T&gt;</c>)</item>
        // </list>
        object[] formatArgs = new object[5];
        foreach (InternalGenerator.Model model in InternalGenerator.Models)
        {
            sb.Clear();
            formatArgs[0] = model.BaseMode;
            formatArgs[1] = model.Mode;
            formatArgs[2] = model.TypeParam;
            formatArgs[3] = model.Constraint is null ? "" : $", {model.TypeParam}";
            formatArgs[4] = model.Constraint is null ? "" : $"<{model.TypeParam}>";
            IndentedTextWriter writer = new(new StringWriter(sb));
            writer.WriteLine(SharedHeader);
            GenerateCore(writer, in model, formatArgs, CollectionHandler.Instance);
            GenerateCore(writer, in model, formatArgs, CollectionReadOnlyHandler.Instance);
            GenerateCore(writer, in model, formatArgs, EnumerableWriteOnlyHandler.Instance);
            GenerateCore(writer, in model, formatArgs, ReadOnlySpanWriteOnlyHandler.Instance);
            string code = sb.ToString();
            context.AddSource($"DefaultHandler/{model.Mode}Handler.g.cs", code);
        }
    }

    private static void GenerateCore(
        IndentedTextWriter writer,
        in InternalGenerator.Model model,
        object[] formatArgs,
        IHandler handler)
    {
        writer.WriteLines(handler.Signature, formatArgs);
        if (!string.IsNullOrEmpty(model.Constraint))
        {
            using (writer.IndentedBlock())
            {
                writer.WriteLine(model.Constraint, formatArgs);
            }
        }
        using (writer.CodeBlock())
        {
            writer.WriteLines(handler.Body, formatArgs);
        }
    }
}