using Microsoft.CodeAnalysis;

namespace Myitian.LiteProtobuf.CompileTimeSourceGeneration.Templates;

static partial class RepeatedUtility
{
    const string SharedHeader = """
        // <auto-generated />
        using System.Numerics;
        using System.Runtime.CompilerServices;
        
        #nullable enable
        
        namespace Myitian.LiteProtobuf;
        
        partial class RepeatedUtility
        """;
    public static void RegisterAll(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(TryRead.Generate);
        context.RegisterPostInitializationOutput(Read.Generate);
        context.RegisterPostInitializationOutput(Write.Generate);
    }
}