namespace Myitian.LiteProtobuf.CompileTimeSourceGeneration.Templates;

public partial class Repeated
{
    public const string ProtobufUtilityHeader = """
        // <auto-generated />
        using System.Numerics;
        using System.Runtime.CompilerServices;
        
        #nullable enable
        
        namespace Myitian.LiteProtobuf;
        
        partial class ProtobufUtility
        """;
    public static readonly Model[] Models = [
        new("T",    "VarInt",       "VarInt",  "where T : IBinaryInteger<T>",                   Write.VarInt.Instance),
        new("T",    "VarIntZigZag", "VarInt",  "where T : IBinaryInteger<T>, ISignedNumber<T>", Write.VarInt.Instance),
        new("T",    "Fixed32",      "Fixed32", "where T : struct",                              Write.Fixed.Instance ),
        new("T",    "Fixed64",      "Fixed64", "where T : struct",                              Write.Fixed.Instance ),
        new("bool", "Bool",         "VarInt",  null,                                            Write.Bool.Instance  )];
    public readonly struct Model(string typeParam, string mode, string realMode, string? constraint, Write.IType type)
    {
        public readonly string TypeParam = typeParam;
        public readonly string Mode = mode;
        public readonly string BaseMode = realMode;
        public readonly string? Constraint = constraint;
        public readonly Write.IType Type = type;
    }
}