<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <LangVersion>latest</LangVersion>
    <Authors>Myitian</Authors>
    <RootNamespace>$(Authors).$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <AssemblyName>$(Authors).$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="Myitian.LiteProtobuf" Version="1.0.0" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteProtobuf\LiteProtobuf.csproj" />
    <ProjectReference Include="..\LiteProtobuf.SourceGeneration\LiteProtobuf.SourceGeneration.csproj" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
