<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <LangVersion>latest</LangVersion>
    <Authors>Myitian</Authors>
    <RootNamespace>$(Authors).$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <AssemblyName>$(Authors).$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.Memory" Version="*" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" />
  </ItemGroup>

</Project>
