namespace Myitian.LiteProtobuf.CompileTimeSourceGeneration;

public partial class Templates
{
    public const string Attributes = $$"""
            // <auto-generated />
            using System;
            namespace {{UtilityGenerator.NS_Myitian_LiteProtobuf_CompileTimeSourceGeneration}};

            #pragma warning disable CS9113
            
            [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            internal sealed class {{UtilityGenerator.N_ReadRepeatedAttribute}}(string mode, bool isValueType, string extraName = "") : Attribute;

            [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            internal sealed class {{UtilityGenerator.N_WriteRepeatedAttribute}}(string mode, bool isValueType) : Attribute;
            """;
    public const string ProtobufUtilityHeader = """
            // <auto-generated />
            using System.Numerics;
            using System.Runtime.CompilerServices;

            #nullable enable

            namespace Myitian.LiteProtobuf;

            partial class ProtobufUtility
            {
            """;
    public const string ProtobufUtilityFooter = """
            }
            """;
}