namespace Myitian.LiteProtobuf.CompileTimeSourceGeneration;

public partial class Templates
{
    public const string Attributes = $$"""
            // <auto-generated />
            using System;
            namespace {{UtilityGenerator.Namespace}};
            
            [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            internal sealed class {{UtilityGenerator.ReadRepeatedAttribute}}(string mode) : Attribute;

            [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            internal sealed class {{UtilityGenerator.WriteRepeatedAttribute}}(string mode) : Attribute;

            [AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = true)]
            internal sealed class {{UtilityGenerator.ShadowVirtualMethodBodyToAttribute}}(Type target, string typeParameter, string parameter) : Attribute;
            """;
    public const string Header = """
            // <auto-generated />
            using System.Numerics;
            using System.Runtime.CompilerServices;

            #nullable enable

            namespace Myitian.LiteProtobuf;

            partial class ProtobufUtility
            {
            """;
    public const string Footer = """
            }
            """;
}