using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Myitian.LiteProtobuf.CompileTimeSourceGeneration;

[Generator]
public class UtilityGenerator : IIncrementalGenerator
{
    public const string Global = "global::";
    public const string N_ReadRepeatedAttribute = $"{nameof(Templates.ReadRepeated)}Attribute";
    public const string N_WriteRepeatedAttribute = $"{nameof(Templates.WriteRepeated)}Attribute";

    public const string NS_Myitian = nameof(Myitian);
    public const string NS_Myitian_LiteProtobuf = $"{NS_Myitian}.{nameof(LiteProtobuf)}";
    public const string NS_Myitian_LiteProtobuf_CompileTimeSourceGeneration = $"{NS_Myitian_LiteProtobuf}.{nameof(CompileTimeSourceGeneration)}";

    public const string FQ_ReadRepeatedAttribute = $"{NS_Myitian_LiteProtobuf_CompileTimeSourceGeneration}.{N_ReadRepeatedAttribute}";
    public const string FQ_WriteRepeatedAttribute = $"{NS_Myitian_LiteProtobuf_CompileTimeSourceGeneration}.{N_WriteRepeatedAttribute}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // new System.Threading.Thread(static () => System.Threading.Thread.Sleep(100000)) { IsBackground = false }.Start(); // Keep console not to close
        context.RegisterPostInitializationOutput(static postInitializationContext =>
            postInitializationContext.AddSource(
                "Attributes.g.cs",
                Templates.Attributes));

        context.RegisterSourceOutput(context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: FQ_ReadRepeatedAttribute,
            predicate: static (syntaxNode, _) => syntaxNode is MethodDeclarationSyntax,
            transform: static (context, _) => new Templates.ReadRepeated.Model(context))
            .Where(static it => it.IsValid), Templates.ReadRepeated.Apply);

        context.RegisterSourceOutput(context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: FQ_WriteRepeatedAttribute,
            predicate: static (syntaxNode, _) => syntaxNode is MethodDeclarationSyntax,
            transform: static (context, _) => new Templates.WriteRepeated.Model(context))
            .Where(static it => it.IsValid), Templates.WriteRepeated.Apply);
    }

    public static int CreateCSharpCode(StringBuilder sb, string usings, INamedTypeSymbol symbol)
    {
        int depth = 0;
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine(usings);
        sb.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(symbol.ContainingNamespace.Name))
        {
            sb.AppendLine()
                .Append("namespace ")
                .Append(symbol.ContainingNamespace.ToDisplayString())
                .AppendLine(";")
                .AppendLine();
        }
        CreateTypeDefCSharpCode(symbol, sb, ref depth);
        return depth;
    }
    public static void CreateTypeDefCSharpCode(INamedTypeSymbol type, StringBuilder sb, ref int depth)
    {
        if (type.ContainingType is not null)
        {
            CreateTypeDefCSharpCode(type.ContainingType, sb, ref depth);
        }
        sb.Append(' ', depth * 4)
            .Append("partial ")
            .Append(type.IsRecord ? "record " : "")
            .Append(type.IsValueType ? "struct " : "class ")
            .Append(type.Name)
            .AppendLine();
        sb.Append(' ', depth * 4)
            .AppendLine("{");
        depth++;
    }
}
