using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Myitian.LiteProtobuf.CompileTimeSourceGeneration;

[Generator]
public class UtilityGenerator : IIncrementalGenerator
{
    public const string Namespace = "Myitian.LiteProtobuf.CompileTimeSourceGeneration";
    public const string ReadRepeatedAttribute = $"{nameof(Templates.ReadRepeated)}Attribute";
    public const string T_ReadRepeatedAttribute = $"{Namespace}.{ReadRepeatedAttribute}";
    public const string WriteRepeatedAttribute = $"{nameof(Templates.WriteRepeated)}Attribute";
    public const string T_WriteRepeatedAttribute = $"{Namespace}.{WriteRepeatedAttribute}";
    public const string ShadowVirtualMethodBodyToAttribute = $"{nameof(Templates.ShadowVirtualMethodBodyTo)}Attribute";
    public const string T_ShadowBodyToAttribute = $"{Namespace}.{ShadowVirtualMethodBodyToAttribute}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
            postInitializationContext.AddSource(
                $"Attributes.g.cs",
                Templates.Attributes));

        context.RegisterSourceOutput(context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: T_ReadRepeatedAttribute,
            predicate: static (syntaxNode, _) => syntaxNode is MethodDeclarationSyntax,
            transform: static (context, _) => new Templates.ReadRepeated.Model(context))
            .Where(it => it.IsValid), Templates.ReadRepeated.Apply);

        context.RegisterSourceOutput(context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: T_WriteRepeatedAttribute,
            predicate: static (syntaxNode, _) => syntaxNode is MethodDeclarationSyntax,
            transform: static (context, _) => new Templates.WriteRepeated.Model(context))
            .Where(it => it.IsValid), Templates.WriteRepeated.Apply);

        context.RegisterSourceOutput(context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: T_ShadowBodyToAttribute,
            predicate: static (syntaxNode, _) => syntaxNode is InterfaceDeclarationSyntax,
            transform: static (context, _) => new Templates.ShadowVirtualMethodBodyTo.Model(context))
            .Where(it => it.IsValid), Templates.ShadowVirtualMethodBodyTo.Apply);
    }

    public static int CreateCSharpCode(StringBuilder sb, string usings, INamedTypeSymbol symbol)
    {
        int depth = 0;
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine(usings);
        sb.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(symbol.ContainingNamespace.Name))
        {
            sb.AppendLine()
                .Append("namespace ")
                .Append(symbol.ContainingNamespace.ToDisplayString())
                .AppendLine(";")
                .AppendLine();
        }
        CreateTypeDefCSharpCode(symbol, sb, ref depth);
        return depth;
    }
    public static void CreateTypeDefCSharpCode(INamedTypeSymbol type, StringBuilder sb, ref int depth)
    {
        if (type.ContainingType is not null)
        {
            CreateTypeDefCSharpCode(type.ContainingType, sb, ref depth);
        }
        sb.Append(' ', depth * 4)
            .Append("partial ")
            .Append(type.IsRecord ? "record " : "")
            .Append(type.IsValueType ? "struct " : "class ")
            .Append(type.Name)
            .AppendLine();
        sb.Append(' ', depth * 4)
            .AppendLine("{");
        depth++;
    }
}
